spring:
  cloud:
    aws:
      credentials:
        instance-profile: false
      endpoint: ${LOCAL_STACK_HOST:http://127.0.0.1:4566}
      region:
        static: sa-east-1
      s3:
        path-style-access-enabled: true
redis:
  host: ${REDIS_HOST:localhost}
  port: 6379

s3:
  project-bucket: projects
  refactored-projects-bucket: refactored-projects

sqs:
  detect-pattern: detect-pattern
  measure-pattern: measure-pattern

server:
  port: 8083
