# fly.toml app configuration file generated for metrics-calculation on 2024-07-28T18:33:39-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'metrics-calculation'
primary_region = 'iad'

[build]

[env]
  AWS_DEFAULT_REGION = 'us-west-2'
  REDIS_HOST = 'redis-10817.c85.us-east-1-2.ec2.cloud.redislabs.com'
  REDIS_PORT = '10817'

[[mounts]]
  source = 'tmp'
  destination = '/tmp'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
