spring:
  threads:
    virtual:
      enabled: true
  cloud:
    aws:
      credentials:
        instance-profile: false
      endpoint: ${LOCAL_STACK_HOST:http://127.0.0.1:4566}
      region:
        static: sa-east-1
      s3:
        path-style-access-enabled: true
  data:
    redis:
      host:  ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}

s3:
  project-bucket: projects
  refactored-project-bucket: refactored-projects

rqueue:
  enabled: true

queue:
  detect-pattern: detect-pattern
  measure-pattern: measure-pattern

server:
  port: 8081


