spring:
  cloud:
    aws:
      credentials:
        instance-profile: false
      endpoint: ${LOCAL_STACK_HOST:http://127.0.0.1:4566}
      region:
        static: sa-east-1
      s3:
        path-style-access-enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
redis:
  host: ${REDIS_HOST:localhost}
  port: 6379

s3:
  project-bucket: projects
  downloader-bucket: refactored-projects

sqs:
  detect-pattern: detect-pattern

retry:
  max-attempts: 5
  delay: 500
  multiplier: 2

server:
  port: 8080
