spring:
  cloud:
    aws:
      credentials:
        instance-profile: false
      endpoint: http://127.0.0.1:4566
      region:
        static: sa-east-1
      s3:
        region: sa-east-1
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
redis:
  host: localhost
  port: 6379

s3:
  project-bucket: projects
  refactored-projects-bucket: refactored-projects

sqs:
  detect-pattern: detect-pattern