spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: archprome
  cloud:
    openfeign:
      client:
        config:
          pulse-client:
            logger-level: full

server:
  port: 8081

services:
  intermediary: localhost:8080

logging:
  level:
    br.com.detection.detectionagent.ws.core.PulseClient: DEBUG

