spring:
  cloud:
    aws:
      credentials:
        instance-profile: false
      endpoint: http://127.0.0.1:4566
      region:
        static: sa-east-1
redis:
  host: localhost
  port: 6379

s3:
  project-bucket: projects
  refactored-projects-bucket: refactored-projects

sqs:
  detect-pattern: detect-pattern
  measure-pattern: measure-pattern

server:
  port: 8081


