spring:
  threads:
    virtual:
      enabled: true
  cloud:
    aws:
      credentials:
        instance-profile: false
      endpoint: ${LOCAL_STACK_HOST:http://127.0.0.1:4566}
      region:
        static: sa-east-1
      s3:
        path-style-access-enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    redis:
      host:  ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

s3:
  project-bucket: ${PROJECT_BUCKET:projects}
  downloader-bucket: ${REFACTORED_PROJECT_BUCKET:refactored-projects}

rqueue:
  enabled: true

queue:
  detect-pattern: detect-pattern

retry:
  max-attempts: 5
  delay: 500
  multiplier: 2

server:
  port: 8080
